export {
    isClassForbiddenError,
    useClassMembersQuery,
    useClassThreadMessagesQuery,
    useClassThreadsBatchQuery,
    useClassThreadsQuery,
    useCreateClassMutation,
    useCreateGroupThreadMutation,
    useJoinClassByInviteCodeMutation,
    useMyClassContextQuery,
    usePostClassMessageMutation,
    useShareGradeResultToClassMutation,
    useSharePrivateChatToClassMutation,
} from "./queries/useClassQueries";
export type {
    AssignTeacherPayload,
    ClassMemberSummary,
    ClassMembersSnapshot,
    ClassRole,
    ClassSummary,
    ClassThread,
    ClassThreadMessage,
    ClassThreadMessageRole,
    ClassThreadType,
    CreateClassPayload,
    JoinClassByCodePayload,
    MyClassContext,
    PostClassMessagePayload,
    PostClassMessageResult,
    ShareGradeResultPayload,
    SharePrivateChatPayload,
} from "./types";
